import { useAuth } from "@/_core/hooks/useAuth";
import { MapView } from "@/components/Map";
import { InstallAppBanner } from "@/components/InstallAppBanner";
import { ThemeToggle } from "@/components/ThemeToggle";
import { PikiSplash } from "@/components/PikiSplash";
import { trpc } from "@/lib/trpc";
import {
  AlertTriangle,
  ArrowLeft,
  BadgeCheck,
  Bell,
  BellRing,
  Bike,
  Camera,
  CheckCircle2,
  ChevronRight,
  Clock3,
  Crosshair,
  FileCheck2,
  FileText,
  LogOut,
  MapPin,
  Menu,
  Navigation,
  Package,
  Power,
  Radio,
  Route,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Upload,
  UserRound,
  Wallet,
  X,
} from "lucide-react";
import type { Map as LeafletMap } from "leaflet";
import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type RiderStatus = "assigned" | "picked_up" | "delivering";
type Tab = "home" | "map" | "earnings" | "profile";
type DocumentType = "dni" | "driver_license" | "insurance";
type InstallPrompt = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };
type BarcodeDetectorLike = { detect: (source: CanvasImageSource) => Promise<Array<{ rawValue?: string }>> };
type Offer = { id: string; restaurant: string; address: string; payout: number; distanceKm: number; etaMinutes: number };
type RiderNotification = { id: string; title: string; body: string; offer?: Offer; createdAt: number; seen: boolean };

declare global { interface Window { BarcodeDetector?: new (options?: { formats?: string[] }) => BarcodeDetectorLike; } }

const stageLabel: Record<RiderStatus, string> = { assigned: "Ir al local", picked_up: "Pedido recogido", delivering: "En ruta" };
const nextStatus: Record<RiderStatus, RiderStatus> = { assigned: "picked_up", picked_up: "delivering", delivering: "delivering" };
const documentLabels: Record<DocumentType, { label: string; detail: string }> = {
  dni: { label: "DNI / NIE", detail: "Documento de identidad vigente" },
  driver_license: { label: "Licencia de conducir", detail: "Permiso compatible con tu vehículo" },
  insurance: { label: "Seguro", detail: "Póliza o justificante vigente" },
};
const money = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" });

function decodeVapidKey(value: string) {
  const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
  const padding = "=".repeat((4 - normalized.length % 4) % 4);
  const raw = atob(normalized + padding);
  return Uint8Array.from(raw, (character) => character.charCodeAt(0));
}

function planRoute(order: { id: string; status: string; restaurant: string; address: string } | undefined, riderPoint: { lat: number; lng: number } | null) {
  const seed = order?.id.split("").reduce((total, value) => total + value.charCodeAt(0), 0) || 7;
  const pickup = { lat: 38.9908 + (seed % 4) * 0.0018, lng: -0.5185 + (seed % 3) * 0.0014 };
  const dropoff = { lat: pickup.lat + 0.0035 + (seed % 2) * 0.001, lng: pickup.lng - 0.003 + (seed % 3) * 0.0007 };
  const rider = riderPoint || { lat: pickup.lat - 0.0022, lng: pickup.lng - 0.0021 };
  const towardsPickup = order?.status === "assigned";
  const target = towardsPickup ? pickup : dropoff;
  const eta = towardsPickup ? 7 + (seed % 5) : 6 + (seed % 6);
  const route = [rider, { lat: (rider.lat + target.lat) / 2 + 0.0008, lng: (rider.lng + target.lng) / 2 - 0.0005 }, target];
  return { rider, pickup, dropoff, route, eta, target, targetLabel: towardsPickup ? `Recogida · ${order?.restaurant || "Local"}` : `Entrega · ${order?.address || "Cliente"}`, nextStep: towardsPickup ? "Ve al establecimiento y confirma la recogida." : "Dirígete al cliente y valida la entrega con PIN o QR." };
}

export default function Riders() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const isRider = user?.role === "rider";
  const [tab, setTab] = useState<Tab>("home");
  const [menuOpen, setMenuOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [incidentOpen, setIncidentOpen] = useState(false);
  const [sosOpen, setSosOpen] = useState(false);
  const [notificationOpen, setNotificationOpen] = useState(false);
  const [assignmentAlert, setAssignmentAlert] = useState<Offer | null>(null);
  const [notifications, setNotifications] = useState<RiderNotification[]>([]);
  const [confirmOrder, setConfirmOrder] = useState<{ id: string; restaurant: string } | null>(null);
  const [installPrompt, setInstallPrompt] = useState<InstallPrompt | null>(null);
  const [deliveryCode, setDeliveryCode] = useState("");
  const [deliveryMethod, setDeliveryMethod] = useState<"pin" | "qr">("pin");
  const [scannerOpen, setScannerOpen] = useState(false);
  const [sosNote, setSosNote] = useState("");
  const [currentPoint, setCurrentPoint] = useState<{ lat: number; lng: number } | null>(null);
  const [incident, setIncident] = useState({ type: "delay" as "delay" | "address" | "safety" | "customer" | "other", notes: "", orderCode: "" });
  const [profileForm, setProfileForm] = useState({ riderName: "", phone: "", vehicle: "bike" as "bike" | "moto" | "car", zone: "" });
  const mapRef = useRef<LeafletMap | null>(null);
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const scanTimer = useRef<number | null>(null);
  const cameraStream = useRef<MediaStream | null>(null);
  const locationWatch = useRef<number | null>(null);
  const lastLocationSent = useRef(0);
  const knownOfferIds = useRef<Set<string> | null>(null);

  const rider = trpc.rider.mine.useQuery(undefined, { enabled: isAuthenticated && isRider, refetchInterval: 15_000 });
  const documents = trpc.rider.documents.useQuery(undefined, { enabled: isAuthenticated && isRider, refetchInterval: 15_000 });
  const operational = rider.data?.status === "active" && rider.data?.documentsStatus === "verified";
  const online = rider.data?.availability === "available";
  const offers = trpc.rider.offers.useQuery(undefined, { enabled: isAuthenticated && isRider && operational && online, refetchInterval: 6_000 });
  const activeOrders = trpc.rider.active.useQuery(undefined, { enabled: isAuthenticated && isRider, refetchInterval: 6_000 });
  const pushConfig = trpc.rider.pushConfig.useQuery(undefined, { enabled: isAuthenticated && isRider });
  const saveProfile = trpc.rider.profile.useMutation({ onSuccess: () => { void rider.refetch(); toast.success("Perfil de rider guardado", { description: "Operaciones revisará tus documentos y zona antes de activarte." }); setProfileOpen(false); } });
  const uploadDocument = trpc.rider.uploadDocument.useMutation({ onSuccess: () => { void documents.refetch(); void rider.refetch(); toast.success("Documento enviado", { description: "El equipo de flota lo revisará desde Operaciones." }); } });
  const setAvailability = trpc.rider.setAvailability.useMutation({ onSuccess: () => { void rider.refetch(); void offers.refetch(); } });
  const reportLocation = trpc.rider.reportLocation.useMutation();
  const claim = trpc.order.claim.useMutation({ onSuccess: () => { toast.success("Pedido aceptado", { description: "Dirígete al local y confirma la recogida al llegar." }); setAssignmentAlert(null); void offers.refetch(); void activeOrders.refetch(); void rider.refetch(); } });
  const progress = trpc.order.updateStatus.useMutation({ onSuccess: () => { toast.success("Estado actualizado"); void activeOrders.refetch(); } });
  const confirmDelivery = trpc.order.confirmDelivery.useMutation({ onSuccess: () => { toast.success("Entrega confirmada", { description: "El pedido y tus ganancias han sido actualizados." }); setConfirmOrder(null); setDeliveryCode(""); stopScanner(); void activeOrders.refetch(); void rider.refetch(); } });
  const report = trpc.rider.reportIncident.useMutation({ onSuccess: () => { toast.success("Incidencia enviada", { description: "El equipo de operaciones ha sido avisado." }); setIncidentOpen(false); setIncident({ type: "delay", notes: "", orderCode: "" }); } });
  const triggerSOS = trpc.rider.triggerSOS.useMutation({ onSuccess: () => { toast.success("SOS enviado", { description: "Operaciones ha recibido la alerta prioritaria." }); setSosOpen(false); setSosNote(""); } });
  const subscribePush = trpc.rider.subscribePush.useMutation({ onSuccess: () => toast.success("Alertas activadas", { description: "Recibirás avisos de nuevos pedidos incluso con la app cerrada." }) });

  const activeOrder = activeOrders.data?.[0];
  const routePlan = useMemo(() => planRoute(activeOrder, currentPoint), [activeOrder, currentPoint]);
  const todayEarnings = (rider.data?.earningsCents || 0) / 100;
  const docsByType = useMemo(() => { const records = new Map<DocumentType, NonNullable<typeof documents.data>[number]>(); for (const document of documents.data || []) if (!records.has(document.type as DocumentType)) records.set(document.type as DocumentType, document); return records; }, [documents.data]);
  const unseenCount = notifications.filter((notice) => !notice.seen).length;

  useEffect(() => {
    const manifest = document.querySelector<HTMLLinkElement>('link[rel="manifest"]');
    const previousManifest = manifest?.href;
    const previousTitle = document.title;
    if (manifest) manifest.href = "/manifest-riders.json";
    document.title = "PIKI Riders";
    const handleInstall = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPrompt); };
    window.addEventListener("beforeinstallprompt", handleInstall);
    return () => { if (manifest && previousManifest) manifest.href = previousManifest; document.title = previousTitle; window.removeEventListener("beforeinstallprompt", handleInstall); };
  }, []);

  useEffect(() => { if (rider.data) setProfileForm({ riderName: rider.data.displayName, phone: rider.data.phone || "", vehicle: rider.data.vehicle, zone: rider.data.zone }); }, [rider.data?.id]);

  useEffect(() => {
    if (!online || !navigator.geolocation) return;
    const send = (position: GeolocationPosition) => {
      const point = { lat: position.coords.latitude, lng: position.coords.longitude };
      setCurrentPoint(point);
      if (Date.now() - lastLocationSent.current < 20_000) return;
      lastLocationSent.current = Date.now();
      reportLocation.mutate({ latitude: point.lat, longitude: point.lng, accuracyMeters: position.coords.accuracy });
    };
    locationWatch.current = navigator.geolocation.watchPosition(send, () => undefined, { enableHighAccuracy: true, maximumAge: 10_000, timeout: 15_000 });
    return () => { if (locationWatch.current !== null) navigator.geolocation.clearWatch(locationWatch.current); locationWatch.current = null; };
  }, [online]);

  useEffect(() => {
    if (!online || !operational) { knownOfferIds.current = null; return; }
    const current = offers.data || [];
    const ids = new Set(current.map((offer) => offer.id));
    if (!knownOfferIds.current) { knownOfferIds.current = ids; return; }
    const newlyAssigned = current.filter((offer) => !knownOfferIds.current?.has(offer.id));
    knownOfferIds.current = ids;
    if (!newlyAssigned.length) return;
    const offer = newlyAssigned[0];
    const notification: RiderNotification = { id: `${offer.id}-${Date.now()}`, title: "Nuevo pedido cerca de ti", body: `${offer.restaurant} · ${offer.distanceKm.toFixed(1)} km · ${offer.etaMinutes} min`, offer, createdAt: Date.now(), seen: false };
    setNotifications((previous) => [notification, ...previous].slice(0, 20));
    setAssignmentAlert(offer);
    if (navigator.vibrate) navigator.vibrate([150, 70, 150]);
  }, [offers.data, online, operational]);

  const sendCurrentLocation = (success?: (point: { lat: number; lng: number }) => void) => {
    if (!navigator.geolocation) return toast.error("Tu dispositivo no permite geolocalización");
    navigator.geolocation.getCurrentPosition(({ coords }) => {
      const point = { lat: coords.latitude, lng: coords.longitude };
      setCurrentPoint(point);
      mapRef.current?.setView([point.lat, point.lng], 16, { animate: true });
      reportLocation.mutate({ latitude: point.lat, longitude: point.lng, accuracyMeters: coords.accuracy });
      success?.(point);
      toast.success("Ubicación actualizada", { description: "Compartida con la operación mientras estás en línea." });
    }, () => toast.error("No pudimos obtener tu ubicación", { description: "Revisa los permisos del navegador." }), { enableHighAccuracy: true, timeout: 12_000 });
  };
  function stopScanner() { if (scanTimer.current !== null) window.clearInterval(scanTimer.current); scanTimer.current = null; cameraStream.current?.getTracks().forEach((track) => track.stop()); cameraStream.current = null; setScannerOpen(false); }
  const startScanner = async () => {
    if (!window.BarcodeDetector) return toast("Escáner no disponible", { description: "Escribe el PIN o pega el código QR del cliente." });
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" }, audio: false });
      cameraStream.current = stream; setScannerOpen(true);
      if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); }
      const detector = new window.BarcodeDetector({ formats: ["qr_code"] });
      scanTimer.current = window.setInterval(async () => {
        if (!videoRef.current) return;
        const codes = await detector.detect(videoRef.current).catch(() => []);
        if (codes[0]?.rawValue) { setDeliveryMethod("qr"); setDeliveryCode(codes[0].rawValue); stopScanner(); toast.success("Código QR leído"); }
      }, 650);
    } catch { toast.error("No pudimos abrir la cámara", { description: "Permite el acceso o usa el PIN de seis cifras." }); }
  };
  const toggleAvailability = () => { if (!operational) return toast.error("Cuenta pendiente de activación", { description: "Completa y envía DNI, licencia y seguro para la validación." }); setAvailability.mutate({ availability: online ? "offline" : "available" }, { onSuccess: () => toast(online ? "Modo desconectado" : "Ya estás disponible", { description: online ? "No recibirás nuevas ofertas." : "Tu ubicación se compartirá mientras estés en línea." }) }); };
  const enableBackgroundAlerts = async () => {
    if (!pushConfig.data?.configured || !pushConfig.data.publicKey) return toast("Alertas en preparación", { description: "El equipo técnico debe activar las credenciales push antes del lanzamiento." });
    if (!("serviceWorker" in navigator) || !("PushManager" in window) || !("Notification" in window)) return toast.error("Este navegador no admite alertas push");
    const permission = await Notification.requestPermission();
    if (permission !== "granted") return toast.error("Permiso no concedido", { description: "Activa las notificaciones de PIKI Riders desde los ajustes del navegador." });
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription() || await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: decodeVapidKey(pushConfig.data.publicKey) });
      const data = subscription.toJSON();
      if (!data.endpoint || !data.keys?.p256dh || !data.keys.auth) throw new Error("Invalid subscription");
      subscribePush.mutate({ endpoint: data.endpoint, p256dh: data.keys.p256dh, auth: data.keys.auth });
    } catch {
      toast.error("No pudimos activar las alertas", { description: "Comprueba tu conexión y vuelve a intentarlo." });
    }
  };
  const installApp = async () => { if (!installPrompt) return toast("Instala desde el menú del navegador", { description: "En Android, abre Chrome → menú ⋮ → Instalar aplicación." }); await installPrompt.prompt(); const choice = await installPrompt.userChoice; if (choice.outcome === "accepted") toast.success("PIKI Riders se está instalando"); setInstallPrompt(null); };
  const submitProfile = () => { if (!profileForm.riderName.trim() || !profileForm.zone.trim()) return toast.error("Añade tu nombre y zona habitual"); saveProfile.mutate({ riderName: profileForm.riderName.trim(), phone: profileForm.phone.trim() || undefined, vehicle: profileForm.vehicle, zone: profileForm.zone.trim() }); };
  const submitIncident = () => { if (incident.notes.trim().length < 4) return toast.error("Describe brevemente lo ocurrido"); report.mutate({ type: incident.type, notes: incident.notes.trim(), orderCode: incident.orderCode.trim() || undefined }); };
  const submitSOS = () => { const send = (latitude?: number, longitude?: number) => triggerSOS.mutate({ orderCode: activeOrder?.id, latitude, longitude, note: sosNote.trim() || undefined }); if (!navigator.geolocation) return send(); navigator.geolocation.getCurrentPosition(({ coords }) => send(coords.latitude, coords.longitude), () => send(), { enableHighAccuracy: true, timeout: 12_000, maximumAge: 20_000 }); };
  const upload = (type: DocumentType, event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (file.size > 5 * 1024 * 1024) return toast.error("El documento debe pesar menos de 5 MB"); if (!["image/jpeg", "image/png", "application/pdf"].includes(file.type)) return toast.error("Sube una imagen JPG/PNG o un PDF"); const reader = new FileReader(); reader.onload = () => uploadDocument.mutate({ type, fileName: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "application/pdf", dataUrl: String(reader.result) }); reader.readAsDataURL(file); };
  const acceptOffer = (offer: Offer) => claim.mutate({ id: offer.id });

  if (loading) return <div className="grid min-h-screen place-items-center bg-[#10251d]"><Radio className="h-7 w-7 animate-pulse text-[#9ed49f]" /></div>;
  if (!isAuthenticated) return <RiderGate title="Tu ruta empieza aquí" description="Inicia sesión con tu cuenta rider para recibir ofertas, gestionar documentos y confirmar entregas." primary="Crear cuenta de rider" onPrimary={() => { window.location.href = "/?account=rider"; }} secondary="Ya tengo cuenta" onSecondary={() => { window.location.href = "/?login=rider"; }} />;
  if (!isRider) return <RiderGate title="Esta cuenta no es de rider" description="La app de Riders usa una cuenta exclusiva de repartidor. Crea una solicitud de alta o cambia a tu cuenta rider para continuar." primary="Solicitar alta de rider" onPrimary={() => { void logout().then(() => { window.location.href = "/?account=rider"; }); }} secondary="Volver a PIKI" onSecondary={() => { window.location.href = "/"; }} />;

  return <div className="piki-app min-h-screen bg-[#f3f7f1] pb-24 text-[#13251b]"><PikiSplash service="riders" />
    <header className="sticky top-0 z-30 border-b border-[#dce7d8] bg-[#fbfdf9]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#1a4030] text-[#c8f0c2]"><Bike className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#5f8068]">PIKI · App independiente</p><h1 className="font-display text-xl font-semibold tracking-[-.04em]">PIKI Riders</h1></div></div><div className="flex items-center gap-2"><ThemeToggle compact /><button onClick={() => { setNotificationOpen(true); setNotifications((all) => all.map((notice) => ({ ...notice, seen: true }))); }} className="relative grid h-9 w-9 place-items-center rounded-full border border-[#d2dfd0] bg-white text-[#385743]" aria-label="Abrir notificaciones">{unseenCount ? <BellRing className="h-4.5 w-4.5" /> : <Bell className="h-4.5 w-4.5" />}{unseenCount > 0 && <span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-[#dc5c35] px-1 text-[10px] font-extrabold text-white">{unseenCount}</span>}</button><button onClick={toggleAvailability} disabled={setAvailability.isPending} className={`flex items-center gap-2 rounded-full px-3.5 py-2 text-xs font-extrabold transition disabled:opacity-60 ${online ? "bg-[#1a4030] text-white" : "bg-white text-[#5e7062] ring-1 ring-[#d2dfd0]"}`}><Power className="h-3.5 w-3.5" /> {online ? "En línea" : "Sin conexión"}</button><button onClick={() => setMenuOpen(true)} className="grid h-9 w-9 place-items-center rounded-full border border-[#d2dfd0] bg-white text-[#385743]" aria-label="Abrir menú"><Menu className="h-4.5 w-4.5" /></button></div></div></header>
    <main className="mx-auto max-w-5xl px-4 py-6 sm:px-6"><InstallAppBanner service="riders" />
      {operational && <section className="mb-6 flex flex-wrap items-center gap-3 rounded-2xl border border-[#cde4ca] bg-[#f7fff5] p-4"><BellRing className="h-5 w-5 text-[#171715]" /><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">Alertas de pedidos en segundo plano</p><p className="mt-0.5 text-xs text-[#5e7462]">Actívalas para recibir nuevos pedidos aunque PIKI Riders esté cerrada.</p></div><button onClick={enableBackgroundAlerts} disabled={subscribePush.isPending} className="rounded-full bg-[#171715] px-3.5 py-2 text-xs font-extrabold text-white disabled:opacity-60">{subscribePush.isPending ? "Activando…" : "Activar alertas"}</button></section>}
      {!operational && <section className="mb-6 rounded-[1.45rem] border border-[#e7bd75] bg-[#fff7e8] p-4"><div className="flex items-start gap-3"><FileCheck2 className="mt-0.5 h-5 w-5 text-[#a76b18]" /><div className="min-w-0 flex-1"><p className="text-sm font-extrabold text-[#72460f]">Activación pendiente</p><p className="mt-1 text-xs leading-relaxed text-[#8a642f]">Completa el perfil y carga DNI, licencia y seguro. Un responsable de flota validará tu cuenta antes de habilitar ofertas.</p></div><button onClick={() => setTab("profile")} className="shrink-0 rounded-full bg-[#a76b18] px-3 py-2 text-xs font-extrabold text-white">Completar</button></div></section>}
      <section className="rounded-[1.7rem] bg-[#143b2b] p-5 text-white shadow-[0_14px_34px_rgba(20,59,43,.18)] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b7d6b9]">{online ? "Disponible en tu zona" : "Tu turno está en pausa"}</p><h2 className="mt-2 font-display text-4xl font-semibold tracking-[-.06em]">Hola, {rider.data?.displayName || user?.name || "rider"}</h2><p className="mt-3 text-sm text-[#d5e8d4]">{rider.data?.zone || "Elige tu zona habitual"} · {rider.data?.vehicle === "bike" ? "Bicicleta" : rider.data?.vehicle === "moto" ? "Moto" : "Coche"}</p></div><button onClick={() => sendCurrentLocation()} className="flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-xs font-extrabold text-white ring-1 ring-white/20"><Crosshair className="h-4 w-4" /> Mi ubicación</button></div><div className="mt-6 grid grid-cols-3 gap-3"><HeroMetric label="Ofertas" value={String(offers.data?.length || 0)} /><HeroMetric label="Activas" value={String(activeOrders.data?.length || 0)} /><HeroMetric label="Hoy" value={money.format(todayEarnings)} /></div></section>
      {tab === "home" && <div className="mt-7 space-y-7"><section><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">Despacho inteligente</p><h3 className="font-display text-3xl font-semibold tracking-[-.05em]">Ofertas listas</h3></div><span className="flex items-center gap-1.5 rounded-full bg-white px-3 py-2 text-xs font-extrabold text-[#40644a] ring-1 ring-[#dce7d8]"><Radio className="h-3.5 w-3.5" /> En vivo</span></div>{operational && online && offers.data?.length ? <div className="space-y-3">{offers.data.map((offer) => <OfferCard key={offer.id} offer={offer} onAccept={() => acceptOffer(offer)} pending={claim.isPending} />)}</div> : <EmptyState icon={Package} title={operational ? online ? "No hay ofertas listas" : "Activa tu disponibilidad" : "Cuenta pendiente de activar"} text={operational ? online ? "Las ofertas se ordenan por cercanía, tiempo estimado y pago." : "Ponte en línea cuando quieras recibir nuevas ofertas." : "Carga los tres documentos requeridos para continuar."} />}</section>
        <section><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">En ruta</p><h3 className="font-display text-3xl font-semibold tracking-[-.05em]">Mis entregas</h3></div><button onClick={() => setIncidentOpen(true)} className="flex items-center gap-1.5 rounded-full bg-[#fff0e9] px-3 py-2 text-xs font-extrabold text-[#a85135]"><AlertTriangle className="h-3.5 w-3.5" /> Reportar</button></div>{activeOrders.data?.length ? <div className="space-y-3">{activeOrders.data.map((order) => { const status = order.status as RiderStatus; const activePlan = planRoute(order, currentPoint); return <article key={order.id} className="rounded-2xl border border-[#d9e6d7] bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h4 className="text-sm font-extrabold">{order.restaurant}</h4><span className="rounded-full bg-[#eaf4e6] px-2 py-1 text-[10px] font-extrabold uppercase tracking-wide text-[#171715]">{stageLabel[status]}</span></div><p className="mt-1 text-xs text-[#69806e]">{order.id} · {order.address}</p></div><Route className="h-5 w-5 text-[#171715]" /></div><div className="mt-3 flex items-center gap-2 rounded-xl bg-[#f4f8f2] p-3 text-xs text-[#4e6654]"><Clock3 className="h-4 w-4 text-[#171715]" /><span className="font-bold">{activePlan.targetLabel}</span><span className="ml-auto font-extrabold">~{activePlan.eta} min</span></div><div className="mt-4 flex flex-wrap items-center gap-3 border-t border-[#edf3eb] pt-3"><button onClick={() => { setTab("map"); window.setTimeout(() => mapRef.current?.setView([activePlan.target.lat, activePlan.target.lng], 14, { animate: true }), 100); }} className="flex items-center gap-1 text-xs font-bold text-[#52735a]"><Navigation className="h-3.5 w-3.5" /> Ver ruta</button><button onClick={() => { if (status === "delivering") { setConfirmOrder({ id: order.id, restaurant: order.restaurant }); setDeliveryCode(""); } else progress.mutate({ id: order.id, status: nextStatus[status] }); }} disabled={progress.isPending} className="ml-auto rounded-full bg-[#171715] px-3.5 py-2 text-xs font-extrabold text-white disabled:opacity-60">{status === "assigned" ? "Confirmar recogida" : status === "picked_up" ? "Salir al cliente" : "Confirmar entrega"}</button></div>{status === "delivering" && <button onClick={() => setSosOpen(true)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-[#fff0e9] py-2.5 text-xs font-extrabold text-[#af4d34]"><ShieldAlert className="h-4 w-4" /> SOS · Necesito ayuda</button>}</article>; })}</div> : <EmptyState icon={Bike} title="Sin entregas activas" text="Acepta una oferta lista para activar tu siguiente ruta." />}</section></div>}
      {tab === "map" && <section className="mt-7 overflow-hidden rounded-[1.6rem] bg-white shadow-sm ring-1 ring-[#dfe8dc]"><div className="flex flex-wrap items-start justify-between gap-3 p-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">Ruta de entrega</p><h3 className="mt-1 font-display text-2xl font-semibold">{activeOrder ? routePlan.targetLabel : "Tu mapa operativo"}</h3><p className="mt-1 text-xs text-[#718076]">{activeOrder ? routePlan.nextStep : "Cuando aceptes un pedido, verás la ruta y su tiempo estimado."}</p></div><button onClick={() => sendCurrentLocation()} className="flex items-center gap-1.5 rounded-full bg-[#eaf4e6] px-3 py-2 text-xs font-extrabold text-[#171715]"><Crosshair className="h-3.5 w-3.5" /> Centrar</button></div>{activeOrder && <div className="mx-4 mb-4 grid grid-cols-3 gap-2 rounded-2xl bg-[#143b2b] p-3 text-white"><RouteMetric label="ETA" value={`~${routePlan.eta} min`} /><RouteMetric label="Siguiente" value={activeOrder.status === "assigned" ? "Local" : "Cliente"} /><RouteMetric label="Estado" value={stageLabel[activeOrder.status as RiderStatus]} /></div>}<MapView initialCenter={routePlan.rider} initialZoom={14} className="h-[480px]" onMapReady={(map) => { mapRef.current = map; }} route={activeOrder ? routePlan.route : []} points={activeOrder ? [{ ...routePlan.rider, label: "Tu ubicación", kind: "rider" }, { ...routePlan.pickup, label: `Recogida · ${activeOrder.restaurant}`, kind: "pickup" }, { ...routePlan.dropoff, label: "Entrega · cliente", kind: "dropoff" }] : currentPoint ? [{ ...currentPoint, label: "Tu ubicación", kind: "rider" }] : []} /><div className="grid gap-3 p-4 sm:grid-cols-2"><div className="rounded-xl bg-[#f5f8f3] p-3"><p className="text-xs font-bold text-[#6b7a6e]">Recogida</p><p className="mt-1 truncate text-sm font-extrabold">{activeOrder?.restaurant || "Aún sin pedido"}</p></div><div className="rounded-xl bg-[#f5f8f3] p-3"><p className="text-xs font-bold text-[#6b7a6e]">Entrega</p><p className="mt-1 truncate text-sm font-extrabold">{activeOrder?.address || "Tu siguiente dirección aparecerá aquí"}</p></div></div></section>}
      {tab === "earnings" && <section className="mt-7 rounded-[1.6rem] bg-white p-5 shadow-sm ring-1 ring-[#dfe8dc] sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">Wallet</p><h3 className="mt-1 font-display text-3xl font-semibold tracking-[-.05em]">Tus ganancias</h3><div className="mt-6 rounded-2xl bg-[#143b2b] p-6 text-white"><p className="text-sm font-bold text-[#cfe2cf]">Acumulado confirmado</p><p className="mt-2 text-5xl font-extrabold tracking-[-.06em]">{money.format(todayEarnings)}</p><p className="mt-3 text-xs text-[#c0d7c1]">Las ganancias se calculan después de cada entrega validada con PIN o QR.</p></div></section>}
      {tab === "profile" && <section className="mt-7 space-y-5"><div className="rounded-[1.6rem] bg-white p-5 shadow-sm ring-1 ring-[#dfe8dc] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">Perfil operativo</p><h3 className="mt-1 font-display text-3xl font-semibold tracking-[-.05em]">Tu cuenta rider</h3></div><button onClick={() => setProfileOpen(true)} className="rounded-full bg-[#eaf4e6] px-3 py-2 text-xs font-extrabold text-[#171715]">Editar perfil</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><StatusCard icon={ShieldCheck} label="Cuenta" value={rider.data?.status === "active" ? "Activa" : rider.data?.status === "suspended" ? "Suspendida" : "Pendiente"} positive={rider.data?.status === "active"} /><StatusCard icon={FileCheck2} label="Validación" value={rider.data?.documentsStatus === "verified" ? "Documentos verificados" : rider.data?.documentsStatus === "rejected" ? "Acción necesaria" : "Pendiente de revisión"} positive={rider.data?.documentsStatus === "verified"} /></div></div><div className="rounded-[1.6rem] bg-white p-5 shadow-sm ring-1 ring-[#dfe8dc] sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">Documentos</p><h3 className="mt-1 font-display text-3xl font-semibold tracking-[-.05em]">Verificación obligatoria</h3><p className="mt-2 text-sm text-[#718076]">Carga archivos legibles. Puedes sustituirlos si caducan o si Operaciones solicita una revisión.</p><div className="mt-6 grid gap-3">{(Object.keys(documentLabels) as DocumentType[]).map((type) => <DocumentCard key={type} type={type} document={docsByType.get(type)} pending={uploadDocument.isPending} onUpload={(event) => upload(type, event)} />)}</div></div></section>}
    </main>
    <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-[#dce7d8] bg-[#fbfdf9]/95 px-3 pb-[max(0.75rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur"><div className="mx-auto flex max-w-md items-center justify-between">{([{ key: "home", label: "Ruta", icon: Bike }, { key: "map", label: "Mapa", icon: MapPin }, { key: "earnings", label: "Wallet", icon: Wallet }, { key: "profile", label: "Perfil", icon: UserRound }] as const).map(({ key, label, icon: Icon }) => <button key={key} onClick={() => setTab(key)} className={`flex min-w-14 flex-col items-center gap-1 rounded-xl px-3 py-1.5 text-[10px] font-extrabold ${tab === key ? "bg-[#eaf4e6] text-[#1a4030]" : "text-[#6c7b6f]"}`}><Icon className="h-4.5 w-4.5" />{label}</button>)}</div></nav>
    {assignmentAlert && <div className="fixed inset-x-4 top-20 z-50 mx-auto max-w-lg rounded-[1.4rem] border border-[#b8d9b5] bg-[#f8fff6] p-4 shadow-2xl"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#171715] text-white"><BellRing className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">Nuevo pedido cerca de ti</p><p className="mt-1 text-xs text-[#5c7360]">{assignmentAlert.restaurant} · {assignmentAlert.distanceKm.toFixed(1)} km · {assignmentAlert.etaMinutes} min al local</p><div className="mt-3 flex gap-2"><button onClick={() => acceptOffer(assignmentAlert)} className="rounded-full bg-[#143b2b] px-3 py-2 text-xs font-extrabold text-white">Aceptar pedido</button><button onClick={() => setAssignmentAlert(null)} className="rounded-full border border-[#d4e2d2] bg-white px-3 py-2 text-xs font-extrabold text-[#586b5d]">Más tarde</button></div></div><button onClick={() => setAssignmentAlert(null)} aria-label="Cerrar alerta"><X className="h-4 w-4 text-[#657768]" /></button></div></div>}
    {notificationOpen && <NotificationCenter notifications={notifications} offers={offers.data || []} onClose={() => setNotificationOpen(false)} onAccept={acceptOffer} />}
    {menuOpen && <div className="fixed inset-0 z-50 bg-[#10251d]/35 backdrop-blur-sm" onMouseDown={() => setMenuOpen(false)}><aside onMouseDown={(event) => event.stopPropagation()} className="ml-auto flex h-full w-full max-w-sm flex-col bg-[#fbfdf9] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">PIKI Riders</p><h2 className="font-display text-3xl font-semibold">Menú</h2></div><button onClick={() => setMenuOpen(false)} className="grid h-10 w-10 place-items-center rounded-full border border-[#dce7d8] bg-white"><X className="h-5 w-5" /></button></div><div className="mt-8 space-y-3"><button onClick={installApp} className="flex w-full items-center gap-3 rounded-2xl bg-[#eaf4e6] p-4 text-left text-[#171715]"><Smartphone className="h-5 w-5" /><span><span className="block text-sm font-extrabold">Instalar app</span><span className="block text-xs opacity-80">Instalación directa desde Chrome en Android</span></span></button><button onClick={() => { setMenuOpen(false); setTab("profile"); }} className="flex w-full items-center gap-3 rounded-2xl bg-white p-4 text-left ring-1 ring-[#dce7d8]"><FileCheck2 className="h-5 w-5 text-[#171715]" /><span><span className="block text-sm font-extrabold">Perfil y documentos</span><span className="block text-xs text-[#718076]">DNI, licencia y seguro</span></span></button><button onClick={() => { setMenuOpen(false); setIncidentOpen(true); }} className="flex w-full items-center gap-3 rounded-2xl bg-[#fff0e9] p-4 text-left text-[#a85135]"><ShieldAlert className="h-5 w-5" /><span><span className="block text-sm font-extrabold">Reportar incidencia</span><span className="block text-xs opacity-80">Retraso, dirección o seguridad</span></span></button></div><div className="mt-auto space-y-3"><Link href="/" className="flex items-center gap-2 p-3 text-sm font-bold text-[#647268]"><ArrowLeft className="h-4 w-4" /> Volver a PIKI</Link><button onClick={() => { void logout().then(() => { window.location.assign("/riders"); }); }} className="flex w-full items-center justify-center gap-2 rounded-xl border border-[#dce7d8] bg-white py-3 text-sm font-extrabold text-[#617164]"><LogOut className="h-4 w-4" /> Cerrar sesión</button></div></aside></div>}
    {profileOpen && <Modal title="Completa tu perfil" onClose={() => setProfileOpen(false)}><p className="text-sm leading-relaxed text-[#6b7a6e]">Estos datos se revisan con tus documentos antes de activar ofertas.</p><div className="mt-6 space-y-4"><Field label="Nombre operativo" value={profileForm.riderName} onChange={(value) => setProfileForm((current) => ({ ...current, riderName: value }))} /><Field label="Teléfono" value={profileForm.phone} type="tel" onChange={(value) => setProfileForm((current) => ({ ...current, phone: value }))} /><label className="block"><span className="mb-1.5 block text-sm font-bold">Vehículo</span><select value={profileForm.vehicle} onChange={(event) => setProfileForm((current) => ({ ...current, vehicle: event.target.value as "bike" | "moto" | "car" }))} className="w-full rounded-xl border border-[#d4e0d2] bg-white px-3 py-3 text-sm outline-none focus:border-[#171715]"><option value="bike">Bicicleta</option><option value="moto">Moto</option><option value="car">Coche</option></select></label><Field label="Zona habitual" value={profileForm.zone} placeholder="Ej. Xàtiva centro" onChange={(value) => setProfileForm((current) => ({ ...current, zone: value }))} /></div><button onClick={submitProfile} disabled={saveProfile.isPending} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#1a4030] py-3.5 text-sm font-extrabold text-white disabled:opacity-60"><CheckCircle2 className="h-4 w-4" /> {saveProfile.isPending ? "Guardando…" : "Guardar perfil"}</button></Modal>}
    {incidentOpen && <Modal title="Reportar incidencia" onClose={() => setIncidentOpen(false)}><p className="text-sm leading-relaxed text-[#6b7a6e]">El equipo de zona recibirá este reporte en Operaciones.</p><div className="mt-6 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-bold">Tipo</span><select value={incident.type} onChange={(event) => setIncident((current) => ({ ...current, type: event.target.value as typeof incident.type }))} className="w-full rounded-xl border border-[#d4e0d2] bg-white px-3 py-3 text-sm outline-none"><option value="delay">Retraso</option><option value="address">Dirección</option><option value="customer">Cliente</option><option value="safety">Seguridad</option><option value="other">Otro</option></select></label><Field label="Código de pedido (opcional)" value={incident.orderCode} placeholder="MG-XXXX" onChange={(value) => setIncident((current) => ({ ...current, orderCode: value }))} /><label className="block"><span className="mb-1.5 block text-sm font-bold">¿Qué ha ocurrido?</span><textarea value={incident.notes} onChange={(event) => setIncident((current) => ({ ...current, notes: event.target.value }))} rows={4} className="w-full resize-none rounded-xl border border-[#d4e0d2] bg-white px-3 py-3 text-sm outline-none" placeholder="Describe el problema" /></label></div><button onClick={submitIncident} disabled={report.isPending} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#b85637] py-3.5 text-sm font-extrabold text-white"><ShieldAlert className="h-4 w-4" /> {report.isPending ? "Enviando…" : "Enviar a operaciones"}</button></Modal>}
    {sosOpen && <Modal title="Alerta SOS" onClose={() => setSosOpen(false)}><div className="rounded-2xl bg-[#fff0e9] p-4 text-sm leading-relaxed text-[#8a4734]"><ShieldAlert className="mb-2 h-6 w-6" /><p className="font-extrabold">Esta acción envía una alerta prioritaria a Operaciones con tu ubicación actual y el pedido en curso.</p></div><label className="mt-5 block"><span className="mb-1.5 block text-sm font-bold">Nota opcional</span><textarea value={sosNote} onChange={(event) => setSosNote(event.target.value)} rows={3} className="w-full resize-none rounded-xl border border-[#e6c5ba] bg-white px-3 py-3 text-sm outline-none" placeholder="Ej. Necesito asistencia en el punto de entrega" /></label><button onClick={submitSOS} disabled={triggerSOS.isPending} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#b33d2b] py-3.5 text-sm font-extrabold text-white"><ShieldAlert className="h-4 w-4" /> {triggerSOS.isPending ? "Enviando SOS…" : "Confirmar y enviar SOS"}</button></Modal>}
    {confirmOrder && <Modal title="Confirmar entrega" onClose={() => { setConfirmOrder(null); stopScanner(); }}><p className="text-sm leading-relaxed text-[#6b7a6e]">Pide al cliente su PIN de seis cifras o escanea el QR de su pantalla. La entrega no se cerrará sin validación.</p><div className="mt-5 grid grid-cols-2 gap-2 rounded-xl bg-[#eef4eb] p-1"><button onClick={() => { stopScanner(); setDeliveryMethod("pin"); }} className={`rounded-lg py-2.5 text-sm font-extrabold ${deliveryMethod === "pin" ? "bg-white text-[#171715] shadow-sm" : "text-[#708070]"}`}>PIN</button><button onClick={() => setDeliveryMethod("qr")} className={`rounded-lg py-2.5 text-sm font-extrabold ${deliveryMethod === "qr" ? "bg-white text-[#171715] shadow-sm" : "text-[#708070]"}`}>QR</button></div>{deliveryMethod === "pin" ? <div className="mt-5"><label className="block"><span className="mb-1.5 block text-sm font-bold">PIN del cliente</span><input value={deliveryCode} onChange={(event) => setDeliveryCode(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" placeholder="000000" className="w-full rounded-xl border border-[#d4e0d2] bg-white px-4 py-4 text-center font-mono text-2xl font-extrabold tracking-[.4em] outline-none focus:border-[#171715]" /></label></div> : <div className="mt-5 space-y-3"><button onClick={startScanner} className="flex w-full items-center justify-center gap-2 rounded-xl border border-[#d4e0d2] bg-white py-3 text-sm font-extrabold text-[#171715]"><Camera className="h-4 w-4" /> Abrir cámara y escanear</button><video ref={videoRef} muted playsInline className={scannerOpen ? "w-full rounded-xl bg-black" : "hidden"} /><label className="block"><span className="mb-1.5 block text-sm font-bold">O pega el código QR</span><input value={deliveryCode} onChange={(event) => setDeliveryCode(event.target.value)} placeholder="MANDUCA:MG-..." className="w-full rounded-xl border border-[#d4e0d2] bg-white px-3 py-3 text-sm outline-none focus:border-[#171715]" /></label></div>}<button onClick={() => confirmDelivery.mutate({ id: confirmOrder.id, method: deliveryMethod, value: deliveryCode })} disabled={confirmDelivery.isPending || !deliveryCode} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#1a4030] py-3.5 text-sm font-extrabold text-white disabled:opacity-60"><BadgeCheck className="h-4 w-4" /> {confirmDelivery.isPending ? "Verificando…" : "Confirmar entrega"}</button></Modal>}
  </div>;
}

function OfferCard({ offer, onAccept, pending }: { offer: Offer; onAccept: () => void; pending: boolean }) { return <article className="rounded-2xl border border-[#d9e6d7] bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#eaf4e6] text-[#171715]"><Package className="h-5 w-5" /></div><div className="min-w-0"><h4 className="truncate text-sm font-extrabold">{offer.restaurant}</h4><p className="mt-1 text-xs font-bold text-[#69806e]">{offer.id} · {offer.distanceKm.toFixed(1)} km · {offer.etaMinutes} min al local</p></div></div><p className="shrink-0 text-sm font-extrabold text-[#171715]">{money.format(offer.payout)}</p></div><div className="mt-4 flex flex-wrap items-center gap-3 border-t border-[#edf3eb] pt-3"><span className="flex min-w-0 items-center gap-1 text-xs font-bold text-[#657568]"><MapPin className="h-3.5 w-3.5 text-[#d95b39]" /> <span className="truncate">{offer.address}</span></span><button disabled={pending} onClick={onAccept} className="ml-auto flex items-center gap-1 rounded-full bg-[#1a4030] px-3.5 py-2 text-xs font-extrabold text-white disabled:opacity-60">Aceptar <ChevronRight className="h-3.5 w-3.5" /></button></div></article>; }
function NotificationCenter({ notifications, offers, onClose, onAccept }: { notifications: RiderNotification[]; offers: Offer[]; onClose: () => void; onAccept: (offer: Offer) => void }) { const notices = notifications.length ? notifications : offers.map((offer) => ({ id: `live-${offer.id}`, title: "Oferta disponible", body: `${offer.restaurant} · ${offer.distanceKm.toFixed(1)} km`, offer, createdAt: Date.now(), seen: true })); return <div className="fixed inset-0 z-[60] bg-[#10251d]/40 backdrop-blur-sm" onMouseDown={onClose}><aside onMouseDown={(event) => event.stopPropagation()} className="ml-auto flex h-full w-full max-w-md flex-col bg-[#fbfdf9] p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">Centro de avisos</p><h2 className="mt-1 font-display text-3xl font-semibold">Notificaciones</h2></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full border border-[#dce7d8] bg-white"><X className="h-5 w-5" /></button></div><div className="mt-6 space-y-3 overflow-y-auto">{notices.length ? notices.map((notice) => <article key={notice.id} className={`rounded-2xl p-4 ${notice.seen ? "bg-white ring-1 ring-[#dce7d8]" : "bg-[#eaf4e6] ring-1 ring-[#b9d9b7]"}`}><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#143b2b] text-white"><BellRing className="h-4.5 w-4.5" /></div><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">{notice.title}</p><p className="mt-1 text-xs text-[#687a6d]">{notice.body}</p>{notice.offer && <button onClick={() => { onAccept(notice.offer!); onClose(); }} className="mt-3 rounded-full bg-[#171715] px-3 py-2 text-xs font-extrabold text-white">Aceptar pedido</button>}</div></div></article>) : <div className="rounded-2xl border border-dashed border-[#cfdcca] p-7 text-center"><Bell className="mx-auto h-6 w-6 text-[#6b8b70]" /><p className="mt-3 text-sm font-extrabold">Sin avisos nuevos</p><p className="mt-1 text-xs text-[#718076]">Las ofertas cercanas aparecerán aquí mientras estás en línea.</p></div>}</div></aside></div>; }
function DocumentCard({ type, document, pending, onUpload }: { type: DocumentType; document?: { status: string; fileName: string; fileUrl: string; reviewNote: string | null }; pending: boolean; onUpload: (event: ChangeEvent<HTMLInputElement>) => void }) { const meta = documentLabels[type]; const tone = document?.status === "verified" ? "bg-[#eaf4e6] text-[#171715]" : document?.status === "rejected" || document?.status === "expired" ? "bg-[#fff0e9] text-[#a85135]" : "bg-[#fff7e8] text-[#9c681b]"; const label = document?.status === "verified" ? "Verificado" : document?.status === "rejected" ? "Reenviar" : document?.status === "expired" ? "Caducado" : document ? "En revisión" : "Pendiente"; return <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-[#dce7d9] p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#f1f5ef] text-[#171715]"><FileText className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-extrabold">{meta.label}</p><span className={`rounded-full px-2 py-1 text-[10px] font-extrabold uppercase tracking-wide ${tone}`}>{label}</span></div><p className="mt-1 text-xs text-[#718076]">{document ? document.fileName : meta.detail}</p>{document?.reviewNote && <p className="mt-1 text-xs font-bold text-[#a85135]">Nota: {document.reviewNote}</p>}</div>{document && <a href={document.fileUrl} target="_blank" rel="noreferrer" className="text-xs font-extrabold text-[#171715]">Ver</a>}<label className="cursor-pointer rounded-full bg-[#143b2b] px-3 py-2 text-xs font-extrabold text-white"><Upload className="mr-1 inline h-3.5 w-3.5" /> {pending ? "Subiendo" : document ? "Sustituir" : "Subir"}<input type="file" accept="image/jpeg,image/png,application/pdf" className="hidden" disabled={pending} onChange={onUpload} /></label></div>; }
function RiderGate({ title, description, primary, secondary, onPrimary, onSecondary }: { title: string; description: string; primary: string; secondary: string; onPrimary: () => void; onSecondary: () => void }) { return <div className="grid min-h-screen place-items-center bg-[#10251d] p-5"><div className="w-full max-w-lg rounded-[2rem] bg-[#f8fbf6] p-8 text-center shadow-2xl sm:p-12"><div className="mx-auto grid h-16 w-16 place-items-center rounded-[1.4rem] bg-[#1a4030] text-[#c8f0c2]"><Bike className="h-8 w-8" /></div><p className="mt-7 text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">PIKI Riders</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-[-.06em]">{title}</h1><p className="mx-auto mt-4 max-w-md text-sm leading-relaxed text-[#647268]">{description}</p><button onClick={onPrimary} className="mt-7 w-full rounded-xl bg-[#1a4030] py-3.5 text-sm font-extrabold text-white">{primary}</button><button onClick={onSecondary} className="mt-3 w-full rounded-xl border border-[#d4e0d2] bg-white py-3 text-sm font-extrabold text-[#171715]">{secondary}</button></div></div>; }
function HeroMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/10 p-3 ring-1 ring-white/10"><p className="text-[10px] font-bold uppercase tracking-wide text-[#bbd6bc]">{label}</p><p className="mt-1 text-xl font-extrabold">{value}</p></div>; }
function RouteMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/10 p-2.5"><p className="text-[9px] font-bold uppercase tracking-wide text-[#bbd6bc]">{label}</p><p className="mt-1 truncate text-xs font-extrabold">{value}</p></div>; }
function EmptyState({ icon: Icon, title, text }: { icon: typeof Package; title: string; text: string }) { return <div className="rounded-2xl border border-dashed border-[#cfddcc] bg-white p-7 text-center"><Icon className="mx-auto h-6 w-6 text-[#6b8b70]" /><p className="mt-3 text-sm font-extrabold">{title}</p><p className="mx-auto mt-1 max-w-sm text-xs leading-relaxed text-[#718076]">{text}</p></div>; }
function StatusCard({ icon: Icon, label, value, positive }: { icon: typeof ShieldCheck; label: string; value: string; positive: boolean }) { return <div className={`rounded-2xl p-4 ${positive ? "bg-[#eaf4e6] text-[#171715]" : "bg-[#fff6ec] text-[#8e692f]"}`}><Icon className="h-5 w-5" /><p className="mt-3 text-xs font-bold opacity-75">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p></div>; }
function Field({ label, value, onChange, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) { return <label className="block"><span className="mb-1.5 block text-sm font-bold">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} type={type} placeholder={placeholder} className="w-full rounded-xl border border-[#d4e0d2] bg-white px-3 py-3 text-sm outline-none focus:border-[#171715]" /></label>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[60] grid place-items-center bg-[#10251d]/45 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-[2rem] bg-[#f8fbf6] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5f8068]">PIKI Riders</p><h2 className="mt-1 font-display text-3xl font-semibold tracking-[-.05em]">{title}</h2></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full border border-[#d4e0d2] bg-white"><X className="h-4 w-4" /></button></div>{children}</div></div>; }
