from pathlib import Path
p=Path('/home/ubuntu/piki-customer/client/src/components/AccountHub.tsx'); s=p.read_text()
s=s.replace('import { startLogin } from "@/const";', 'import { startLogin } from "@/const";\nimport { startRegistration, startAuthentication } from "@simplewebauthn/browser";')
s=s.replace('  const pending = register.isPending || login.isPending || requestReset.isPending || resetPassword.isPending;', '  const pending = register.isPending || login.isPending || requestReset.isPending || resetPassword.isPending;\n  const [passkeyBusy, setPasskeyBusy] = useState(false);\n  const activatePasskey = async () => {\n    try { setPasskeyBusy(true); const options = await fetch("https://api.pikidelivery.com/api/v1/passkeys/customer/register/options", { method: "POST", credentials: "include" }).then((r) => r.json()); if (options.error) throw new Error(options.error); const credential = await startRegistration({ optionsJSON: options }); const result = await fetch("https://api.pikidelivery.com/api/v1/passkeys/customer/register/verify", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(credential) }).then((r) => r.json()); if (!result.verified) throw new Error(result.error || "PASSKEY_REGISTRATION_FAILED"); toast.success("Inicio biométrico activado", { description: "La próxima vez podrás entrar con huella, Face ID o el bloqueo del dispositivo." }); } catch (error) { toast.error("No se pudo activar la biometría", { description: error instanceof Error ? error.message : "Prueba desde un dispositivo compatible." }); } finally { setPasskeyBusy(false); }\n  };\n  const loginWithPasskey = async () => {\n    try { setPasskeyBusy(true); const options = await fetch("https://api.pikidelivery.com/api/v1/passkeys/customer/auth/options", { method: "POST", credentials: "include" }).then((r) => r.json()); const assertion = await startAuthentication({ optionsJSON: options }); const result = await fetch("https://api.pikidelivery.com/api/v1/passkeys/customer/auth/verify", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(assertion) }).then((r) => r.json()); if (!result.verified) throw new Error(result.error || "PASSKEY_AUTHENTICATION_FAILED"); await utils.auth.me.invalidate(); setPanel(null); toast.success("Sesión iniciada"); } catch (error) { toast.error("No se pudo iniciar con biometría", { description: error instanceof Error ? error.message : "Usa tu contraseña." }); } finally { setPasskeyBusy(false); }\n  };')
needle='</div><button onClick={() => { void logout().then(() => { toast.success("Sesión cerrada"); setPanel(null); }); }}'
replacement='</div><div className="rounded-2xl border border-[#e3d9cf] bg-white p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-[#16856f]" /><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">Huella, Face ID o PIN del dispositivo</p><p className="mt-1 text-xs leading-relaxed text-[#69766c]">Activa Passkey para entrar más rápido sin guardar contraseñas en PIKI.</p></div></div><button disabled={passkeyBusy} onClick={activatePasskey} className="mt-3 w-full rounded-xl bg-[#171715] py-2.5 text-xs font-extrabold text-white disabled:opacity-60">{passkeyBusy ? "Configurando…" : "Activar inicio biométrico"}</button></div><button onClick={() => { void logout().then(() => { toast.success("Sesión cerrada"); setPanel(null); }); }}'
if needle not in s: print('PROFILE_NEEDLE_NOT_FOUND')
else: s=s.replace(needle,replacement)
# Add biometric option to login after main login button
needle2='{pending ? "Entrando…" : "Iniciar sesión"}</button><div className="mt-5 flex items-center'
replacement2='{pending ? "Entrando…" : "Iniciar sesión"}</button><button type="button" disabled={passkeyBusy} onClick={loginWithPasskey} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[#ded5ca] bg-white py-3 text-sm font-extrabold text-[#314037] disabled:opacity-60"><ShieldCheck className="h-4 w-4 text-[#16856f]" />{passkeyBusy ? "Comprobando…" : "Entrar con huella / Face ID"}</button><div className="mt-5 flex items-center'
if needle2 not in s: print('LOGIN_NEEDLE_NOT_FOUND')
else: s=s.replace(needle2,replacement2)
p.write_text(s)
