from pathlib import Path
p=Path('/home/ubuntu/piki-customer/client/src/pages/Home.tsx'); s=p.read_text()
s=s.replace('  const [addressDraft, setAddressDraft] = useState(address);', '  const [addressDraft, setAddressDraft] = useState(address);\n  const [locationSuggestions, setLocationSuggestions] = useState<Array<{ label: string; latitude: number; longitude: number }>>([]);\n  const [locationsLoading, setLocationsLoading] = useState(false);')
needle='  const cartCount = cart.reduce((total, line) => total + line.quantity, 0);'
insert='''  useEffect(() => {\n    const query = addressDraft.trim();\n    if (query.length < 3 || !addressOpen) { setLocationSuggestions([]); return; }\n    const controller = new AbortController(); const timer = window.setTimeout(async () => {\n      setLocationsLoading(true);\n      try { const response = await fetch(`https://api.pikidelivery.com/api/v1/locations/search?q=${encodeURIComponent(query)}`, { signal: controller.signal }); const payload = await response.json(); setLocationSuggestions(payload.results || []); } catch {} finally { setLocationsLoading(false); }\n    }, 300);\n    return () => { window.clearTimeout(timer); controller.abort(); };\n  }, [addressDraft, addressOpen]);\n\n'''
s=s.replace(needle,insert+needle)
old='''      {addressOpen && <div className="fixed inset-0 z-[70] grid place-items-center bg-[#171715]/45 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-[2rem] bg-[#FFFDF5] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#dc5c35]">Zona de entrega</p><h2 className="font-display text-3xl font-semibold tracking-[-.05em]">¿Dónde estás?</h2></div><button onClick={() => setAddressOpen(false)} className="grid h-9 w-9 place-items-center rounded-full border border-[#e5dbd0] bg-white"><X className="h-4 w-4" /></button></div><div className="mt-6 rounded-2xl border border-[#e9dfd5] bg-white p-3"><label className="flex items-center gap-3"><MapPin className="h-5 w-5 text-[#FFD72E]" /><input autoFocus value={addressDraft} onChange={(event) => setAddressDraft(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none" aria-label="Dirección de entrega" /></label></div><div className="mt-3 flex items-start gap-2 rounded-xl bg-[#FFF4BE] p-3 text-xs leading-relaxed text-[#526952]"><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-[#171715]" />La selección y los tiempos se ajustan a tu zona.</div><button onClick={() => { if (addressDraft.trim().length < 5) { toast.error("Escribe una dirección más completa"); return; } setAddress(addressDraft.trim()); setAddressOpen(false); toast.success("Dirección actualizada"); }} className="mt-6 w-full rounded-xl bg-[#171715] py-3.5 text-sm font-extrabold text-white transition hover:bg-[#050505]">Ver opciones disponibles</button></div></div>}'''
new='''      {addressOpen && <div className="fixed inset-0 z-[70] grid place-items-center bg-[#171715]/45 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-[2rem] bg-[#FFFDF5] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#dc5c35]">Zona de entrega</p><h2 className="font-display text-3xl font-semibold tracking-[-.05em]">¿Dónde estás?</h2><p className="mt-1 text-xs text-[#68746a]">Busca cualquier calle de Xàtiva, pedanía o localidad de la Comunitat Valenciana.</p></div><button onClick={() => setAddressOpen(false)} className="grid h-9 w-9 place-items-center rounded-full border border-[#e5dbd0] bg-white"><X className="h-4 w-4" /></button></div><div className="mt-6 rounded-2xl border border-[#e9dfd5] bg-white p-3"><label className="flex items-center gap-3"><MapPin className="h-5 w-5 text-[#FFD72E]" /><input autoFocus value={addressDraft} onChange={(event) => setAddressDraft(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none" aria-label="Calle, número, localidad o código postal" placeholder="Calle, número, localidad o CP" /></label></div>{locationsLoading && <p className="mt-3 text-xs font-semibold text-[#68746a]">Buscando calles y localidades…</p>}{locationSuggestions.length > 0 && <div className="mt-2 max-h-52 overflow-y-auto rounded-2xl border border-[#e9dfd5] bg-white p-1">{locationSuggestions.map((suggestion) => <button key={`${suggestion.latitude}-${suggestion.longitude}-${suggestion.label}`} onClick={() => { setAddressDraft(suggestion.label); setLocationSuggestions([]); }} className="flex w-full items-start gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-semibold text-[#314037] hover:bg-[#FFF4BE]"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-[#dc5c35]" /><span>{suggestion.label}</span></button>)}</div>}<div className="mt-3 flex items-start gap-2 rounded-xl bg-[#FFF4BE] p-3 text-xs leading-relaxed text-[#526952]"><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-[#171715]" />La selección y los tiempos se ajustan a tu zona. Los resultados proceden del buscador geográfico de PIKI.</div><button onClick={() => { if (addressDraft.trim().length < 5) { toast.error("Escribe una dirección más completa"); return; } setAddress(addressDraft.trim()); setAddressOpen(false); toast.success("Dirección actualizada"); }} className="mt-6 w-full rounded-xl bg-[#171715] py-3.5 text-sm font-extrabold text-white transition hover:bg-[#050505]">Ver opciones disponibles</button></div></div>}'''
if old not in s: print('ADDRESS_BLOCK_NOT_FOUND')
else: s=s.replace(old,new)
p.write_text(s)
